title: Brett Stark
author: brettstark73
email: brett@brettstark.com
description: > # this means to ignore newlines until "baseurl:"
  Test site for Brett Stark. Learning GitHub pages.

# social links
twitter_username: brettstark
github_username:  brettstark73

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
